name: Continuous Story Generator

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration to run in hours (0 for unlimited)'
        required: true
        default: '24'
      stories_count:
        description: 'Number of stories to generate (0 for unlimited)'
        required: true
        default: '10'

jobs:
  generate-stories:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 hours max timeout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up environment secrets
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV
          
      - name: Run continuous story generator
        env:
          DURATION_HOURS: ${{ github.event.inputs.duration }}
          STORIES_COUNT: ${{ github.event.inputs.stories_count }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python continuous_runner.py --duration $DURATION_HOURS --count $STORIES_COUNT
          
      - name: Upload generated content
        uses: actions/upload-artifact@v3
        with:
          name: generated-stories
          path: |
            output/
            *.log
          retention-days: 7
