name: Continuous Story Generator

on:
  # Run daily at midnight UTC (can be adjusted to your preferred time)
  schedule:
    - cron: '0 0 * * *'  # Format: minute hour day month day-of-week
  
  # Keep manual trigger option
  workflow_dispatch:
    inputs:
      duration:
        description: 'Duration to run in hours (0 for unlimited)'
        required: true
        default: '2.34'  # Set default to 2 hours and 34 minutes
      stories_count:
        description: 'Number of stories to generate (0 for unlimited)'
        required: true
        default: '0'  # Set to unlimited by default to focus on time

jobs:
  generate-stories:
    runs-on: ubuntu-latest
    timeout-minutes: 154  # 2 hours and 34 minutes (2.34 hours * 60 = 140.4 minutes, rounded to 154 with buffer)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up environment secrets
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV
          
      - name: Run continuous story generator
        env:
          # If triggered manually, use the input values; otherwise use scheduled values
          DURATION_HOURS: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.duration || '2.34' }}
          STORIES_COUNT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.stories_count || '0' }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Running for ${DURATION_HOURS} hours or until ${STORIES_COUNT} stories are generated (0 = unlimited)"
          python continuous_runner.py --duration $DURATION_HOURS --count $STORIES_COUNT
          
      - name: Upload generated content
        uses: actions/upload-artifact@v2
        with:
          name: generated-stories
          path: |
            output/
            *.log
          retention-days: 7
